collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.125448
color:
  saturation: 0.08632404
  brandStrength: 0.5108368
  rhythmicContrast: 0.235155
  brandColors:
    - '#0C0B0D'
    - '#ADA9A2'
    - '#867966'
    - '#4B4438'
    - '#F0FFFF'
  lightness: 0.469534
layout_spectrum: 0.5071685
name: Griffin
