purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4375
  brandStrength: 0.5108368
  rhythmicContrast: 0.25
  brandColors:
    - '#0C0B0D'
    - '#ADA9A2'
    - '#867966'
    - '#4B4438'
    - '#F0FFFF'
  lightness: 0.469534
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Griffin
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.125448
layout_spectrum: 0.3440135
